apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-26T16:31:29Z"
  labels:
    type: dev
  name: nginx-deploy
  namespace: default
  resourceVersion: "45448"
  uid: ce8f6e9f-a7a6-485c-bc97-48e67de06d02
spec:
  clusterIP: 10.102.31.53
  clusterIPs:
  - 10.102.31.53
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31713
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    type: dev
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

